/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-data-store.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

declare namespace LogicElements {

  /**
   * An element that offers access to the datastore for ARC objects.
   */
  class ImportDataStore extends PolymerElement {
    readonly _savedDb: any;
    readonly _historyDb: any;
    readonly _projectsDb: any;
    readonly _socketUrlDb: any;
    readonly _urlDb: any;
    readonly _variablesDb: any;
    readonly _variablesEnvsDb: any;
    readonly _headersSetsDb: any;
    readonly _cookiesDb: any;
    readonly _authDataDb: any;
    readonly _hostRulesDb: any;

    /**
     * Imports data into the data store.
     *
     * @param exportObj Normalized export object
     * @returns Promise resolved to list of error messages, if any.
     */
    importData(exportObj: object|null): Promise<any>|null;
    importRequests(requests: any): any;
    importProjects(projects: any): any;
    importHistory(history: any): any;
    importWebsocketUrls(urls: any): any;
    importUrls(urls: any): any;
    importCookies(data: any): any;
    importAuthData(data: any): any;
    importHeaders(data: any): any;
    importHostRules(data: any): any;
    importVariables(data: any): any;
    importEnvironments(data: any): any;
    _importEnvironments(variables: any): any;
    _handleInsertResponse(result: any, items: any, db: any): any;
    _handleConflictedInserts(db: any, conflicted: any): any;

    /**
     * Lists all requests that should be added to URL index.
     * It builds an array of requests are required by `arc-models/url-indexer`
     * element.
     *
     * @param result PouchDB bulk insert response
     * @param requests Inserted requests
     * @param type Request type, `saved` or `history`
     */
    _listRequestIndex(result: Array<object|null>|null, requests: Array<object|null>|null, type: String|null): Array<object|null>|null|undefined;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "import-data-store": LogicElements.ImportDataStore;
  }
}
