/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   transformers-import.html
 */

/// <reference path="transformers/base-transformer.d.ts" />
/// <reference path="transformers/arc-dexie-transformer.d.ts" />
/// <reference path="transformers/arc-legacy-transformer.d.ts" />
/// <reference path="transformers/arc-pouch-transformer.d.ts" />
/// <reference path="transformers/postman-transformer.d.ts" />
/// <reference path="transformers/postman-backup-transformer.d.ts" />
/// <reference path="transformers/postman-v1-transformer.d.ts" />
/// <reference path="transformers/postman-v2-transformer.d.ts" />
/// <reference path="transformers/postman-env-transformer.d.ts" />
/// <reference path="transformers/postman-data-transformer.d.ts" />
/// <reference path="arc-data-import.d.ts" />

