/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   test/postman/postman-data-tranformer-backup.test.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PostmanBackupTransformer} from '../../transformers/postman-backup-transformer.js';
