/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   test/postman/postman-data-tranformer-v1.test.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PostmanV1Transformer} from '../../transformers/postman-v1-transformer.js';
