/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   transformers/postman-data-transformer.js
 */

/**
 * jshint -W098
 */
declare class PostmanDataTransformer {
  transform(data: any): any;
  recognizeVersion(data: any): any;
}
